default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

# test:
#   <<: *default
#   username: <%= ENV["DB_UNAME"] %>
#   password: <%= ENV["DB_PWD"] %>
#   # Please don't use ENV["DATABASE_URL"] here. When you run test, it will create your database..
#   database: gebeya_test_db

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
